spring.application.name=parqueadero

# ===============================
# DATASOURCE - POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/parqueadero_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# LOGS SQL
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# JACKSON / SERVER
# ===============================
spring.jackson.time-zone=America/Bogota
server.port=8080